### ISSUE TITLE
aviso de alerta no console JS do navegador

### ISSUE THREAD

**Issue by valessiobrito** [govbr/barra.govbr#1]
analisando o console JS do navegador, recebo esse aviso:

Pedido entre origens bloqueado: a política de mesma origem proíbe a leitura de recursos remotos em http://barra.brasil.gov.br/static/opensans-bold.woff. Isto pode ser corrigido movendo-se o recurso para o mesmo domínio ou ativando o CORS. opensans-bold.woff

downloadable font: download failed (font-family: "Open Sans" style:normal weight:bold stretch:normal src index:2): bad URI or cross-site access not allowed
source: http://barra.brasil.gov.br/static/opensans-bold.woff

**Comment by brosig** [comment]
Esse erro tem aparecido constantemente para mim no Chrome (Versão 67.0.3396.99 - 64 bits), no Firefox (61.0.1 - 64-bit) e Safari (Versão 11.1 (13605.1.33.1.4)).
macOs 10.13.4
Tenho a impressão que voltou recentemente esse problema.

**Comment by caduvieira** [comment]
Versão 2.2.13 corrige o erro que voltou. 

https://softwarepublico.gov.br/gitlab/govbr/barra-govbr/issues/5#note_17181

**Comment by brosig** [comment]
Pra mim o erro voltou na versão 2.2.20.
Voltou para mais alguém?
