### ISSUE TITLE
Ícone de Burger Icon é png e fica pixelado em displays retina

### ISSUE THREAD

**Issue by sahrosa** [govbr/barra.govbr#10]
Olá!
Percebi que o burger icon da Barra Brasil é um png que fica pixelado. Uma sugestão seria usar o ícone-fonte do Font Awesome: http://fortawesome.github.io/Font-Awesome/icon/bars/

O que acham?

**Comment by nicholasio** [comment]
Acho que não seria uma boa ideia incluir o Font-Awesome só para isso, iria aumentar o peso da barra sem necessidade...

**Comment by sahrosa** [comment]
Verdade @nicholasio! E se fosse um svg? :)

**Comment by nicholasio** [comment]
Ai seria uma melhor alternativa, tem que ver só quais browsers/versão a Barra pretende suportar e saber se todos eles suportam SVG.

**Comment by valessiobrito** [comment]
:+1:   lembrando que também é possível fazer ele somente com CSS3 no uso de "gradientes".

**Comment by sahrosa** [comment]
Ótima ideia @valessiobrito :)

**Comment by caduvieira** [comment]
Escolhi via CSS para melhor se adaptar pois ainda temos que dar suporte ao IE8. Podem dar uma olhada no barra.governoeletronico.gov.br/teste para dar opiniões sobre o menu.

**Comment by valessiobrito** [comment]
@caduvieira muito bom trabalho!   Só achei largo demais. Sugiro usar:  width: 20px;   Também remover "left:0px" para "right: 5px;"  assim fica posicionado na direita.    Por fim, troca a cor das barras #000 para um tom cinza #999  e :hover remove o background cinza, aplicando a cor da barra #000 ... vai ficar bonitinho.  :+1:

**Comment by sahrosa** [comment]
Muito bom @caduvieira! E ótimas dicas @valessiobrito, concordo em tudo! Eu só sugeriria usar o #606060 ao invés de #999 para seguir as cores dos outros itens da Barra Brasil! 

E mais uma adição apenas, no meu celular e computador (ambos Chrome) está mostrando as três barrinhas desalinhadas (conforme print abaixo). 

![screenshot_2015-05-04-13-42-24](https://cloud.githubusercontent.com/assets/2932644/7458283/96652af6-f269-11e4-82fa-baa4523f1353.png)

**Comment by valessiobrito** [comment]
@caduvieira tenta usar pixel para fixar largura das barrinhas;  Acho que o espaçamento vai ser mais complicado.

**Comment by caduvieira** [comment]
@valessiobrito @sahrosa Feito. Estará na próxima versão.

**Comment by sahrosa** [comment]
Show!!
