### ISSUE TITLE
Migrar Barra Brasil para Software Público?

### ISSUE THREAD

**Issue by valessiobrito** [govbr/barra.govbr#11]
O novo portal do Software Público esta no AR;  Lá temos ferramentas como gitlab, lista de discussões, comunidade (rede social), etc..

Acredito que "apesar" de ser somente uma barra padrão;  É uma tecnologia em potêncial para ser adotado em outras esferas do governo e também por outros paises.

Essa Issue trata de disso, criar o cadastro do projeto Barra Brasil no portal do Software Público e criar um mirror do repositório por lá.  Vamos unir forças a plataforma que agora também é de colaboração no código.

Att,
Valessio Brito

**Comment by caduvieira** [comment]
Isso já foi levantado no MP. Principalmente por que o @softwarepublico possui uma conta aqui no Github e está publicando softwares aqui.

**Comment by caduvieira** [comment]
Barra migrada para https://portal.softwarepublico.gov.br/gitlab/govbr/barra-govbr
Se puder dar uma luz como manter o github e gitlab em sync será muito apreciado :)
