### ISSUE TITLE
Logos no footer-brasil estão pixelados

### ISSUE THREAD

**Issue by sahrosa** [govbr/barra.govbr#12]
Olá pessoal, 
tínhamos um cartão no repositório do Portal de Serviços sobre os logos do footer-brasil estarem pixelados. O cartão é este: https://github.com/servicosgovbr/portal-de-servicos/issues/350

Consegui os logos em svg com o @almeidafab, aqui tem o [logo de Acesso a Informação](http://www.acessoainformacao.gov.br/lai-para-sic/sic-apoio-orientacoes/guias-e-orientacoes/marca.zip) e aqui o [logo Brasil Pátria Educadora] (http://www.secom.gov.br/atuacao/publicidade/marca-de-governo) ambos em SVG.

Ao tentar editar, cheguei na questão de que usamos o footer pronto de vocês, então não consigo mudar isso. 

Vocês podem dar uma olhada? :)
Obrigada!

**Comment by almeidafab** [comment]
acho q o @caduvieira pode nos ajudar nessa.

**Comment by caduvieira** [comment]
Os logos não estão em svg na barra devido a necessidade de dar suporte ao IE8.

Encontrei algumas sugestões mas atrasam o carregamento do site
https://css-tricks.com/svg-fallbacks/

O melhor seria dar acabar com o suporte para o IE8 e utilizar SVG.

Vou conversar ainda com o @HudsonMesquita .

**Comment by caduvieira** [comment]
@sahrosa sabe qual eh a porcentagem de usuários do portal de serviços que usam o ie8?

**Comment by sahrosa** [comment]
Oi @caduvieira, vou olhar na segunda e te confirmo! :)

**Comment by caduvieira** [comment]
Beleza

**Comment by sahrosa** [comment]
Oi @caduvieira. Vi aqui que 8% utilizam IE, mas não estou conseguindo verificar qual versão... vou verificar amanhã se tem algum outro jeito de encontrar essa informação!

**Comment by caduvieira** [comment]
A barra vai deixar de ter suporte ao ie8 ,9 e 10 com a falta de suporte pela própria Microsoft a esses navegadores. A alteração da barra já foi feita. Falta o rodapé.

**Comment by caduvieira** [comment]
Rodapé está avançando com o SVG.
Live em:
http://barra.governoeletronico.gov.br/teste/
