### ISSUE TITLE
Bootstrap + Barra Brasil quebra elementos de CSS

### ISSUE THREAD

**Issue by nitaibezerra** [govbr/barra.govbr#13]
![38fef782-69c6-11e5-97b6-938f6224a960](https://cloud.githubusercontent.com/assets/1244443/11271360/8b76e672-8eac-11e5-9f02-15891bb95b7c.png)
A aplicação da barraem páginas desenvolvidas com bootstrap sempre quebra alguns elementos de CSS.
Issue relacionada: https://github.com/culturagovbr/id-cultura/issues/8

**Comment by caduvieira** [comment]
Tem alguma página teste que eu já possa verificar?

**Comment by nitaibezerra** [comment]
http://id.cultura.gov.br/

**Comment by caduvieira** [comment]
Corrigido na versão 2.1.6
