### ISSUE TITLE
Erro com o jQuery em modo 'noConflict' (campanha do mosquito)

### ISSUE THREAD

**Issue by hvianna** [govbr/barra.govbr#14]
A atualização com a campanha do mosquito está causando erro em nossos sites em WordPress, o qual utiliza o jQuery em modo "noConflict".

Acredito que seja simples de solucionar, substituindo as chamadas `$(document).ready(function() {` por `jQuery(document).ready(function($) {` no código javascript da barra.

Exemplo de site com problema: http://wp.ufpel.edu.br/cra/

Referências:
http://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/
https://digwp.com/2011/09/using-instead-of-jquery-in-wordpress/

**Comment by hvianna** [comment]
Acabei de ver que o mesmo erro ocorre também no próprio site da campanha - http://combateaedes.saude.gov.br/

**Comment by caduvieira** [comment]
Corrigido na versão 2.1.7
