### ISSUE TITLE
Barra apresenta erro de java script

### ISSUE THREAD

**Issue by rafa7oliveira** [govbr/barra.govbr#15]
A barra apresenta erro após a atualização para a versão 2.1.8 nesta parte do código fonte: 
t=t||$().jquery,i=r.replace(p,"")

Erro no navegador:
Uncaught TypeError: $ is not a function

**Comment by caduvieira** [comment]
Nova versão 2.1.9 do código corrige esse problema. 
https://github.com/govbr/barra.govbr/blob/01627e5b68010109cf57696ab0b8effc45df06e1/recipes/default/assets/barra-brasil.coffee

**Comment by caduvieira** [comment]
@rafa7oliveira pode testar novamente? dá ctrl+f5 para forçar baixar novamente o barra.js

**Comment by rafa7oliveira** [comment]
Resolvido o problema. Parabéns pela campanha. Ficou muito bom.
