### ISSUE TITLE
Erro de javascript

### ISSUE THREAD

**Issue by rafa7oliveira** [govbr/barra.govbr#19]
Ao carregar a Barra Aparece o seguinte Erro: 

barra.js?cor=verde:1 Uncaught TypeError: a.createTextNode is not a function

Quando o Cookie "vasoPlantaCounter" atinge o valor 2, o erro não acontece.

Endereço do site: [http://www.formiga.ifmg.edu.br/](http://www.formiga.ifmg.edu.br/)

**Comment by caduvieira** [comment]
Corrigido em https://github.com/govbr/barra.govbr/commit/a81e1848cc8cdbc463785b0471b456bc065de6a2

Pode testar em barra.governoeletronico.gov.br/teste/barra.js
