### ISSUE TITLE
Não é possivel acessar o link do Vlibras pela barra 

### ISSUE THREAD

**Issue by garotadpi** [govbr/barra.govbr#23]
Tá dando problema na barra o menu do Vlibras, ele fica por baixo, não importa se adicionamos !important ao Z-index, não está dando para acessar o link.

Vi o problema em Firefox Mac OS 45.0.2 e mobile Android 5.1.1

Sugiro simplificar o código para:
![tela](https://cloud.githubusercontent.com/assets/5618318/15074438/620a3476-1375-11e6-8fbb-b55e138585de.png)

``<a title="Acessível em Libras" href="http://vlibras.gov.br/" class="logo-vlibras"><img href="" alt="VLibras"></a> ``

**Comment by caduvieira** [comment]
Isso foi detectado e corrigido no dia 05 mesmo em https://github.com/govbr/barra.govbr/commit/f56561c3e3c1df39207f8134dabe82adefb5f316. Está feito na versão 2.1.19 e aguardando o SERPRO desde então para subir em produção.

**Comment by caduvieira** [comment]
@garotadpi tem algum site especifico para testar ? Sei que no planejamento está com problema. Tem algum outro?

**Comment by caduvieira** [comment]
Subiu nova versão. 2.1.19 e está funcionando corretamente.
