### ISSUE TITLE
Novos relatos devem ser abertos aqui ou em https://softwarepublico.gov.br/gitlab/govbr/barra-govbr/?

### ISSUE THREAD

**Issue by idgserpro** [govbr/barra.govbr#25]
Consta no repositório que esse repositório foi migrado para https://softwarepublico.gov.br/gitlab/govbr/barra-govbr/, mas ele continua a ter atividade aqui no github. Como o git é distribuído, acreditamos que isso é apenas um mirror, correto?

No caso, não seria o caso de fecharmos o recurso desse repositório para abertura de issues e centralizá-los em https://softwarepublico.gov.br/gitlab/govbr/barra-govbr/? Antes de abrirmos o relato https://softwarepublico.gov.br/gitlab/govbr/barra-govbr/issues/1, ficamos na dúvida sobre qual repositório usar.

**Comment by caduvieira** [comment]
Pode utilizar aqui ou no software público para abrir issues. Isso para deixar qualquer cidadão contribuir sem precisar cadastrar no software público ou no github, deixando esse cadastro a critério dele.

**Comment by idgserpro** [comment]
Ok! Obrigado pelo retorno!
