### ISSUE TITLE
Qual a melhor forma de atender a diretiva "É importante ressaltar que o primeiro link da página deve ser o de ir para o conteúdo." usando a barra de governo?

### ISSUE THREAD

**Issue by idgserpro** [govbr/barra.govbr#27]
Seguindo as regras da barra hoje em http://barra.governoeletronico.gov.br/:

```
Habilitando a barra na página

Cole este código logo após a abertura da tag <body>.
```

Não conseguimos atender a [Recomendação 1.5 – Fornecer âncoras para ir direto a um bloco de conteúdo](http://emag.governoeletronico.gov.br/#r1.5), pois o primeiro link passa a ser o "Atualize sua barra" se não tiver javascript e, se tiver, passa a ser o link do brasil.gov.br.

No brasil.gov.temas o @caduvieira fez [uma modificação](https://github.com/plonegovbr/brasil.gov.temas/commit/8033373ec152d9caa3026107dd999d149a4ba7cf#diff-b7977cf34206f8facf114ac5d6795021L22) que atende a essa determinação do e-mag, mas achamos que esse tipo de informação deveria também estar presente em http://barra.governoeletronico.gov.br/ para as pessoas que não usam o IDG (ou alguma outra solução, se houver). O que acham?

**Comment by caduvieira** [comment]
Você está falando sobre colocar a modificação no manual? Vou fazer um teste e colocar para aprovação da comunidade.

**Comment by idgserpro** [comment]
Sim, no manual. Só não sabemos o melhor texto, rs. Seria `Cole este código logo após o primeiro link (<a>) após a abertura da tag <body>, de forma a atender a [Recomendação 1.5 – Fornecer âncoras para ir direto a um bloco de conteúdo](http://emag.governoeletronico.gov.br/#r1.5) do e-mag.` ou fica muito confuso?
