### ISSUE TITLE
O vlibras esta dando problema com do topo da página

### ISSUE THREAD

**Issue by renataigarashi** [govbr/barra.govbr#30]
![vlibras](https://user-images.githubusercontent.com/21979981/34948477-5dcca7a6-f9f4-11e7-8e33-dd3f1daf386a.JPG)

Todo link que esse vlibras cobre, deixou de funcionar... Mesmo quando essa imagem não é mostrada, os links continuam inativos.

**Comment by renataigarashi** [comment]
Verifiquei agora e já esta funcionando normal

**Comment by caduvieira** [comment]
Relacionado com o #29. Já foi corrigido na versão 2.2.10 mas a mesma ainda não subiu para produção. Não posso subir sozinho e estou esperando os responsáveis para subir. Se quiser pode testar no barra.governoeletronico.gov.br/teste

**Comment by renataigarashi** [comment]
Ah, que bom, obrigada pelo retorno e no aguardo.
