### ISSUE TITLE
Erro de acesso misto no Chrome

### ISSUE THREAD

**Issue by hvianna** [govbr/barra.govbr#31]
Quando a barra é inserida em um site acessado via HTTPS o Chrome exibe um erro de conteúdo misto (no console) para o endereço http://eselo-prd.brazilsouth.cloudapp.azure.com:8080/buscar-avaliacao

**Comment by caduvieira** [comment]
Essa chamada já foi retirada na versão 2.2.10.

https://github.com/govbr/barra.govbr/commit/447eb0cab0c9668d68f18d952cc711929070e179

Tenta atualizar a barra no seu cache

**Comment by hvianna** [comment]
Ah, de fato! Resolvido, obrigado!

**Comment by idgserpro** [comment]
Um pequeno "ajuste" que você pode fazer na sua aplicação se for necessário forçar a baixar a nova barra é adicionar um parâmetro qualquer, aí o browser entende que é um "novo recurso" e baixa novamente automaticamente. Exemplo: ao invés de https://barra.brasil.gov.br/barra.js voce chama por https://barra.brasil.gov.br/barra.js?êv=puHeiP8U.
