### ISSUE TITLE
Rodapé automatizado impossibilita fazer assinatura conjunta

### ISSUE THREAD

**Issue by valessiobrito** [govbr/barra.govbr#6]
Considerando o manual de Marca do Governo Federal, versão Jan/2015[1]

O rodapé que agora esta sendo automatizado juntamente com a barra de governo prejudicou a aplicação de assinatura conjunta. (p16 - 1.13, Manual Marca GF)

[1] http://www.secom.gov.br/orientacoes-gerais/publicidade/manual-da-marca-do-gf-jan-2015.pdf

Proposta para solução:
Orientar o órgão adicionar uma ou mais CLASS abrevidas na DIV do rodapé qual orienta o script renderizar as assinaturas conjuntas quais foram indicadas.  Exemplo:
````
<div id="footer-brasil" class="mj mj-sal"></div>
````
Renderiza o footer com a Marca do Governo seguido da assinatura em conjunto do Ministério da Justiça (mj) e depois da Secretaria de Assuntos Legislativos (mj-sal).  Caso seja somente (mj), será somente do Ministerio da Justiça;  caso seja mais de uma Secretaria, outra sigla deve ser inserida, exemplo:  (mj mj-sal mj-snj)  mj-snj = Secretaria Nacional de Justiça

Acredito que seja possível renderizar todas as siglas, imagens e código de estilo através do script para montar a partir de um template SVG, convertendo para outros formatos.

**Comment by garotadpi** [comment]
Valessio;
Podemos levar a proposta a SECOM. Mas a ideia do manual é - até onde eu saiba - para peças impressas.

**Comment by valessiobrito** [comment]
@garotadpi acredito que precisa ser feita uma avaliação sobre esse assunto. "Todos querem assinar no final";  Outra vantagem;  É que o uso desse artfício pode oferecer para SECOM uma relação de quantos e quais órgãos já adotaram esse padrão (através do mapeamento de quantas tags estão sendo carregadas).

**Comment by HudsonMesquita** [comment]
@valessiobrito, conversei com a SECOM a respeito da assinatura conjunta no rodapé e o entendimento deles é que não seria necessário, pois, pela IDG, a identificação do órgão é feita no cabeçalho, e logos de marcas e programas de governo podem ser inseridas no miolo das páginas, sem necessidade de usar o rodapé.

**Comment by valessiobrito** [comment]
@HudsonMesquita Muito obrigado pelo retorno e atenção.  Dito isso, fecho essa Issue.
