### ISSUE TITLE
z-index da .list de links abaixo do cabeçalho 

### ISSUE THREAD

**Issue by valessiobrito** [govbr/barra.govbr#9]
Como comentado no pull request https://github.com/govbr/barra.govbr/pull/3#issuecomment-76550719

O item .list ficou abaixo de itens do cabeçalho; é preciso adicionar em ```` #barra-brasil .list ```` o valor de ordem ```` z-index: 9; ````.

Bug do screenshot.
![captura de tela de 2015-02-28 19 10 37](https://cloud.githubusercontent.com/assets/310049/6428349/f34ea716-bf7d-11e4-9a0a-94022f36f5c7.png)

**Comment by caduvieira** [comment]
Foi feito no 2.1.3 e já está em produção. https://github.com/govbr/barra.govbr/blob/master/CHANGES.md
